### PR TITLE
removed jekyll.yml | 3.8 iteration

### PR DESCRIPTION
**Pull request by nikhilsna**
SCRUM Master: Nikhil

Group members: Elliot Y Hithin P Armaghan Z

### CODE REVIEW

**Comment by jm1021** [comment]
image

Out of bounds.  Do not change my about.md

**Comment by nikhilsna** [comment]
Hi Mr. Mortensen, I'm not sure what you mean.

https://github.com/nighthawkcoders/portfolio_2025/actions

My group never touched the about.md file

**Comment by jm1021** [comment]
Look at "Files Changed" above.  You have about.md in the request.

**Comment by nikhilsna** [comment]
Apologies, one of my group members changed it. I changed back

**Pull request closed without merging**
